### PR TITLE
Fix #10538 - Cannot swap a std.typecons.Tuple

### LINKED ISSUE #10538: Cannot swap a std.typecons.Tuple
### Description

````markdown
enum x = (){
    import std.algorithm, std.typecons;
    Tuple!int a, b;
    swap(a, b);
    return 0;
}();

/usr/include/dmd/phobos/std/algorithm/mutation.d(2836): Error: reinterpreting cast from `Tuple!int*` to `ubyte*` is not supported in CTFE

First reported here:
https://issues.dlang.org/show_bug.cgi?id=21429#c2

This also applies for any struct T that satisfies isBlitAssignable yet `hasElaborateAssign!T || !isAssignable!T` is true.

PR incoming.
````

### PR DESCRIPTION
**Pull request by ntrel**
Avoid CTFE unsafe cast by swapping elements of `tupleof`.

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by schveiguy** [comment]
this needs effort to make it pass CI. It should not be automerged by accident. Should be reviewed after being fixed.

**Comment by thewilsonator** [comment]
Please retitle the _commit message_ "Fix bugzilla issue 24285 - ..."

**Comment by LightBender** [comment]
@ntrel `typecons` is coming up for Phobos 3. Is there any chance we can get this merged soon so that we don't have to duplicate this fix?

**Comment by 0xEAB** [comment]
Backup copy of the previous commits on the branch: <https://github.com/0xEAB/phobos/tree/ntrel/swap-ctfe-backup>

**Comment by 0xEAB** [comment]
AFACIT, apart from the sumtype breakage that is pointed out by CI, this fails at least this test: <https://github.com/dlang/phobos/blob/336bed6d8ffec74d117b755866c5bd22e3d610a1/std/algorithm/sorting.d#L2145>

File: std/algorithm/mutation.d [hunk 1]
```diff
@@ -3128,6 +3139,25 @@ if (isBlitAssignable!T && !is(typeof(lhs.proxySwap(rhs))))
...
+        return 0;
+    }();
+}
+
+/// ditto
+void swap(T)(ref T lhs, ref T rhs)
+if (is(typeof(lhs.proxySwap(rhs))))
+{
+    lhs.proxySwap(rhs);
+}
```
Comment (0xEAB) [inline std/algorithm/mutation.d:3159]: @ntrel
What was this overload supposed to solve?

Comment (0xEAB) [reply std/algorithm/mutation.d]: Unfortunately, I haven’t been able to figure that out myself.
All I can tell is that it breaks this code:
https://github.com/dlang/phobos/blob/336bed6d8ffec74d117b755866c5bd22e3d610a1/std/algorithm/sorting.d#L2145

File: std/typecons.d [hunk 2]
```diff
@@ -980,24 +980,35 @@ if (distinctFieldNames!(Specs))
...
             import std.algorithm.mutation : swap;
 
-            static if (is(R == Tuple!Types) && !__traits(isRef, rhs) && isTuple!R)
+            /*
+                This optimization caused compilation failures with no error message available:
+
+                > Error: unknown, please file report on issues.dlang.org
+                > std/sumtype.d(1262): Error: template instance `std.sumtype.SumType!(Flag, Tuple!(This*))` error instantiating
+            */
+            version (none)
```
Comment (0xEAB) [inline std/typecons.d:989]: This was awful to debug. I’d love if someone could track this down and open a DMD bug report.

**Review by thewilsonator — APPROVED** [review]
