### PR TITLE
Fix #10699 - std.format with position with omitted second number does not work

### LINKED ISSUE #10699: std.format with position with omitted second number does not work
It's specified in https://dlang.org/library/std/format.html section "Position":
- _It is also possible to denote a series of arguments with two numbers separated by ':', that are all processed in the same way._
- _The second number can be omitted. In that case the series ends with the last argument._

The latter case, with an omitted second number, does not work: It throws an exception at runtime.

**How to reproduce:**
```
import std.stdio;
import std.format;

void main ()
{
  writeln (format ("%1$x %+2:9$d", 11, 22, 33, 44, 55, 66, 77, 88, 99));
  writeln (format ("%1$x %+2:$d", 11, 22, 33, 44, 55, 66, 77, 88, 99));
}
```
Run this program with dmd 2.110.

Expected output:
```
b +22+33+44+55+66+77+88+99
b +22+33+44+55+66+77+88+99
```

Actual output:
```
b +22+33+44+55+66+77+88+99
std.format.FormatException@/usr/include/dmd/phobos/std/format/write.d(651): Positional specifier %2$d index exceeds 9
----------------
??:? pure @safe uint std.format.write.formattedWrite!(std.array.Appender!(immutable(char)[]).Appender, char, int, int, int, int, int, int, int, int, int).formattedWrite(ref std.array.Appender!(immutable(char)[]).Appender, scope const(char[]), int, int, int, int, int, int, int, int, int) [0x63a71565a545]
??:? pure @safe immutable(char)[] std.format.format!(char, int, int, int, int, int, int, int, int, int).format(in char[], int, int, int, int, int, int, int, int, int) [0x63a7156599ad]
??:? _Dmain [0x63a715659930]
```

### PR DESCRIPTION
**Pull request by rikkimax**
Increases the ``startIndex`` and ``endIndex`` types to ``ushort``, documents that the maximum value is now used as a sentinel (was previously, but not documented nor worked).

### CODE REVIEW

File: std/format/spec.d [hunk 1]
```diff
@@ -127,14 +127,16 @@ if (is(Unqual!Char == Char))
...
      */
-    ubyte indexStart;
+    ushort indexStart;
 
     /**
        Index of the last argument for positional parameter ranges.
 
        Counting starts with `1`. Set to `0` if not used. Default: `0`.
+
+       The maximum value of this field is used as a sentinal to indicate the arguments length.
```
Comment (pbackus) [inline std/format/spec.d:137]:
```suggestion
       The maximum value of this field is used as a sentinel to indicate the arguments' length.
```

**Review by thewilsonator — APPROVED** [review]
