### PR TITLE
Fix #10565: Prevent negative zero when multiplying BigInt zero by neg…

### LINKED ISSUE #10565: BigInt multiplication of 0 by integral (non-BigInt) type creates "-0" (negative zero)
### Description

Overview:

When multiplying a BigInt `0` by a negative, basic type (e.g. `-1` and `cast(byte)(-1)`), the resulting BigInt is `-0` (negative zero), which creates unexpected behavior.

It is likely a logical error in the `isIntegral!y` variant of the mutating `opOpAssign` method (https://github.com/dlang/phobos/blob/9771a247f540ad0f16822bbffbb1724e218915ba/std/bigint.d#L268), which in turn is propagated to the non-mutating `opAssign` method (https://github.com/dlang/phobos/blob/9771a247f540ad0f16822bbffbb1724e218915ba/std/bigint.d#L524); I imagine the linked conditional in `opOpAssign` should read something like `if(y == 0 || data == 0UL)` to prevent the sign being erroneously set for multiplication from `0`, but I am not sure what the best modification should be.

The appearance of `-0` (negative zero) appears to be a mistake, as evidenced by the resolved and fixed https://issues.dlang.org/show_bug.cgi?id=22771.

Steps to Reproduce:

Tested in the latest version of D (DMD64 D Compiler v2.109.1) and on https://run.dlang.io/

MWE demonstrating the bug, and when it occurs:
```d
import std.stdio : writeln;
import std.bigint;

void main() {
  BigInt a = BigInt("0");                    // 0
  BigInt b = BigInt("-0");                   // 0
  BigInt c = BigInt("0") * -1;               // -0
  BigInt d = BigInt("0") * -42;              // -0
  BigInt e = BigInt("0"); e *= -1;           // -0
  BigInt f = BigInt(c);                      // -0
  BigInt g = BigInt("0") * cast(byte) -1;    // -0
  BigInt h = BigInt("0"); h *= BigInt("-1"); // 0
  BigInt i = BigInt("0"); i -= 2 * i;        // 0
  BigInt j = BigInt("0"); j = -j;            // 0
          
  BigInt[] test = [a,b,c,d,e,f,g,h,i,j];

  foreach(idx, t; test) {
    char id = "abcdefghij"[idx];
    writeln("`", id, "` = ", t);
    writeln("  Is `", id, "` negative? ", t < 0);
    writeln("  Is `", id, "` zero?     ", t == 0);
  }
}
```

### PR DESCRIPTION
**Pull request by dhawal543**
**### Fix for BigInt multiplication of 0 by integral (non-BigInt) type creating "-0" (negative zero)**

**Issue Description**
When multiplying a BigInt with value 0 by a negative integral type (e.g. -1 or cast(byte)(-1)), the resulting BigInt incorrectly becomes "-0" (negative zero), which leads to unexpected behavior. A BigInt with value zero should always have a positive sign regardless of operations performed on it.

**Root Cause**
The issue is in the opOpAssign method for the multiplication operator when handling integral types. Currently, when multiplying by zero, the code sets the data to 0 but still updates the sign based on the operand's sign. This is incorrect mathematical behavior since zero multiplied by any number should be positive zero.

**Fix**
The solution is to modify the opOpAssign method to check both if the operand is zero OR if the BigInt's data is already zero. In either case, we set the sign to false (positive) and the data to zero.

### CODE REVIEW

File: std/bigint.d [hunk 1]
```diff
@@ -264,18 +264,19 @@ public:
...
-                sign = false;
-                data = 0UL;
-            }
-            else
-            {
-                sign = ( sign != (y<0) );
-                data = BigUint.mulInt(data, u);
-            }
-        }
+{
```
Comment (thewilsonator) [inline std/bigint.d:267]: please fix the indentation

**Review by thewilsonator — COMMENTED** [review]
Please also add a unittest for this

**Review by thewilsonator — APPROVED** [review]

File: std/bigint.d [hunk 2]
```diff
@@ -421,6 +422,31 @@ public:
...
+    BigInt b = BigInt("-0");
+    BigInt c = BigInt("0") * -1;
+    BigInt d = BigInt("0") * -42;
+    BigInt e = BigInt("0"); e *= -1;
+    BigInt f = BigInt(c);
+    BigInt g = BigInt("0") * cast(byte) -1;
+    BigInt h = BigInt("0"); h *= BigInt("-1");
+    BigInt i = BigInt("0"); i -= 2 * i;
+    BigInt j = BigInt("0"); j = -j;
+
```
Comment (thewilsonator) [inline std/bigint.d:439]:
```
Check for trailing whitespace
grep -nr '[[:blank:]]$' $(find etc std -name '*.d'); test $? -eq 1
std/bigint.d:439:
```

I'm not entirely sure why the style checker fails here, there doesn't appear to be extra whitespace.

**Comment by thewilsonator** [comment]
You removed the unittest.

**Comment by dhawal543** [comment]
> You removed the unittest.

its there
