### PR TITLE
Fix issue #10858 - Documentation of `std.logger`: `trace()` does not work by default

### LINKED ISSUE #10858: Documentation of `std.logger`: `trace()` does not work by default
Unlike other logging methods, `trace()` doesn't outputs anything even if `globalLogLevel` is set without specifying this magic line:
```d
(cast()sharedLog).logLevel = LogLevel.trace;

```
This is very deeply buried knowledge and I didn't find this in the documentation
Why is it designed by this way? Can anyone improve documentation at this direction?

### PR DESCRIPTION
**Pull request by 0xEAB**
Adds a quick start guide to the package documentation of `std.logger`.
This guide explains the basics and an apparent major pitfall of the module in a casual way.

Fixes #10858.

### CODE REVIEW

**Comment by 0xEAB** [comment]
Not a native speaker, please proofread.

File: std/logger/package.d [hunk 1]
```diff
@@ -24,6 +24,76 @@ This will print a message to the `stderr` device. The message will contain
...
+}
+-------------
+
+$(H5 Rationale)
+
+$(UL
+    $(LI $(LINK2 https://github.com/dlang/phobos/pull/8336, GitHub: dlang/phobos Pull request #8336))
+    $(LI $(LINK2 https://github.com/dlang/phobos/pull/8406, GitHub: dlang/phobos Pull request #8406))
+    $(LI $(LINK2 https://github.com/dlang/phobos/issues/10858, GitHub: dlang/phobos Issue #10858))
+    $(LI $(LINK2 https://web.archive.org/web/20251123060539/https://issues.dlang.org/show_bug.cgi?id=22532, Bugzilla Issue 22532 (archived))
```
Comment (thewilsonator) [inline std/logger/package.d]: I believe the bugzilla is back up now

Comment (Herringway) [reply std/logger/package.d]: seems to be down right now

Comment (0xEAB) [reply std/logger/package.d]: It's barely reachable for me: <https://forum.dlang.org/post/zmpavtigyqdpsccvwbgb@forum.dlang.org>
Also, the outages seem to differ by connection origin.
At this point, I'd rather link the *Wayback Machine* or *Archive.is*.

Comment (0xEAB) [reply std/logger/package.d]: I’ve replaced the *Wayback Machine* link with *bugzilla-archive.dlang.org*.

Comment (0xEAB) [reply std/logger/package.d]: *\*ping\** @thewilsonator

**Review by thewilsonator — APPROVED** [review]

**Comment by denizzzka** [comment]
@0xEAB Thank you very much!
